"""
Model tests on problems whose answer is known in advance.

A model that merely runs proves nothing. Each test below confronts a model with a
situation whose correct outcome is known independently: linear regression must
recover the exact coefficients of a noiseless linear relation, KNN with k=1 must
reclassify its own training points perfectly, logistic regression must separate
two clearly separable clouds, K-Means must find three well-separated groups.

Run:  python tests/test_models.py
"""

import os
import sys

import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))

from src.methods.knn import KNN                                          # noqa: E402
from src.methods.linear_regression import LinearRegression               # noqa: E402
from src.methods.logistic_regression import LogisticRegression           # noqa: E402
from src.methods.kmeans import KMeans                                    # noqa: E402
from src.methods.baselines import MajorityClassBaseline, MeanRegressor   # noqa: E402
from src.utils import accuracy_fn, mse_fn                                # noqa: E402

failures = 0
checks = 0


def check(condition, message):
    global failures, checks
    checks += 1
    if not condition:
        failures += 1
        print(f"FAIL: {message}")


# ---------------------------------------------------------------------------
# Linear regression: recover an exact relation
# ---------------------------------------------------------------------------

def test_linear_regression_noiseless():
    """
    On data generated by y = Xw with no noise, least squares must reconstruct y
    exactly. A non-zero MSE would mean the linear solve is wrong.
    """
    rng = np.random.default_rng(0)
    X = rng.normal(size=(200, 4))
    w_true = np.array([[2.0], [-1.0], [0.5], [3.0]])
    y = X @ w_true

    model = LinearRegression()
    model.fit(X, y)
    error = mse_fn(model.predict(X).ravel(), y.ravel())
    check(error < 1e-20, f"noiseless linear regression: MSE {error:.2e} should be 0")


def test_linear_regression_recovers_coefficients():
    """
    Beyond predictions, the learned WEIGHTS must be the true ones, bias included:
    on y = 4 + Xw with no noise, the pseudo-inverse must return exactly [4, w].
    """
    rng = np.random.default_rng(1)
    X = rng.normal(size=(100, 3))
    w_true = np.array([2.0, -3.0, 0.5])
    y = 4.0 + X @ w_true

    model = LinearRegression()
    model.fit(X, y)
    expected = np.concatenate([[4.0], w_true])
    gap = float(np.max(np.abs(model.weights - expected)))
    check(gap < 1e-10, f"coefficients recovered (bias included): max gap {gap:.2e}")


def test_regression_beats_the_mean():
    """A real model must clearly beat the constant mean predictor."""
    rng = np.random.default_rng(2)
    X = rng.normal(size=(150, 3))
    y = X @ np.array([[1.0], [-2.0], [0.5]]) + rng.normal(scale=0.2, size=(150, 1))

    model = LinearRegression()
    model.fit(X, y)
    model_mse = mse_fn(model.predict(X).ravel(), y.ravel())

    floor = MeanRegressor()
    floor.fit(X, y.ravel())
    floor_mse = mse_fn(floor.predict(X), y.ravel())

    check(model_mse < floor_mse / 2,
          f"linear regression ({model_mse:.3f}) should clearly beat the mean ({floor_mse:.3f})")


# ---------------------------------------------------------------------------
# KNN
# ---------------------------------------------------------------------------

def test_knn_k1_memorises():
    """
    With k=1 every training point is its own nearest neighbour, so predictions on
    the training set must be perfect. This catches bugs in the distance or sort.
    """
    rng = np.random.default_rng(3)
    X = rng.normal(size=(60, 3))
    y = rng.integers(0, 3, size=60)

    model = KNN(k=1)
    model.fit(X, y)
    check(accuracy_fn(model.predict(X), y) == 100.0,
          "KNN with k=1 must reclassify its training points perfectly")


def test_knn_separated_clouds():
    """Two far-apart clouds must be separated perfectly."""
    rng = np.random.default_rng(4)
    X = np.vstack([rng.normal(loc=-10.0, scale=0.3, size=(30, 2)),
                   rng.normal(loc=+10.0, scale=0.3, size=(30, 2))])
    y = np.array([0] * 30 + [1] * 30)

    model = KNN(k=3)
    model.fit(X, y)
    check(accuracy_fn(model.predict(X), y) == 100.0, "KNN must separate two far-apart clouds")


# ---------------------------------------------------------------------------
# Logistic regression
# ---------------------------------------------------------------------------

def test_logistic_separable():
    """
    Two linearly separable classes must be learned almost perfectly, and in any
    case far better than the majority-class floor.
    """
    rng = np.random.default_rng(5)
    X = np.vstack([rng.normal(loc=-3.0, scale=0.5, size=(80, 2)),
                   rng.normal(loc=+3.0, scale=0.5, size=(80, 2))])
    y = np.array([0] * 80 + [1] * 80)

    model = LogisticRegression(lr=0.01, max_iters=500)
    model.fit(X, y)
    acc = accuracy_fn(model.predict(X), y)
    check(acc > 95.0, f"logistic regression on separable data: {acc:.1f}% should exceed 95%")

    floor = MajorityClassBaseline()
    floor.fit(X, y)
    check(acc > accuracy_fn(floor.predict(X), y), "logistic regression must beat the majority floor")


# ---------------------------------------------------------------------------
# K-Means
# ---------------------------------------------------------------------------

def test_kmeans_finds_the_groups():
    """
    Three well-separated clouds: K-Means with K=3 must find them, and therefore
    classify correctly after majority voting.
    """
    rng = np.random.default_rng(6)
    X = np.vstack([
        rng.normal(loc=[0.0, 0.0], scale=0.3, size=(40, 2)),
        rng.normal(loc=[10.0, 0.0], scale=0.3, size=(40, 2)),
        rng.normal(loc=[5.0, 10.0], scale=0.3, size=(40, 2)),
    ])
    y = np.array([0] * 40 + [1] * 40 + [2] * 40)

    model = KMeans(K=3, max_iters=100)
    model.fit(X, y)
    acc = accuracy_fn(model.predict(X), y)
    check(acc > 95.0, f"K-Means on 3 separated clouds: {acc:.1f}% should exceed 95%")


if __name__ == "__main__":
    test_linear_regression_noiseless()
    test_linear_regression_recovers_coefficients()
    test_regression_beats_the_mean()
    test_knn_k1_memorises()
    test_knn_separated_clouds()
    test_logistic_separable()
    test_kmeans_finds_the_groups()

    if failures == 0:
        print(f"PASS: {checks} checks, 0 failures")
        sys.exit(0)
    print(f"FAIL: {failures} failure(s) out of {checks} checks")
    sys.exit(1)
